mod all_categories;
mod create_category;
mod create_post;
mod create_reply;
mod edit_category;
mod edit_post;
mod edit_reply;
mod lock_post;
mod post_from_id;
mod posts_from_category;
mod remove_category;
mod remove_post;
mod remove_reply;
mod replies_from_post;

pub use all_categories::route as all_categories_route;
pub use create_category::route as create_category_route;
pub use create_post::route as create_post_route;
pub use create_reply::route as create_reply_route;
pub use edit_category::route as edit_category_route;
pub use edit_post::route as edit_post_route;
pub use edit_reply::route as edit_reply_route;
pub use lock_post::route as lock_post_route;
pub use post_from_id::route as post_from_id_route;
pub use posts_from_category::route as posts_from_category_route;
pub use remove_category::route as remove_category_route;
pub use remove_post::route as remove_post_route;
pub use remove_reply::route as remove_reply_route;
pub use replies_from_post::route as replies_from_post_route;
